version: '2'

networks:
  cryptocurrency:
    driver: bridge

services:
  # es:
  #   container_name: crypto-elasticsearch
  #   build: docker/elasticsearch/
  #   volumes:
  #     - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx512m -Xms512m"
  #   networks:
  #     - cryptocurrency

  mysql:
    image: mysql
    container_name: crypto-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_ROOT_PASSWORD: InstanceExample!
    networks:
      - cryptocurrency

  # logstash:
  #   container_name: crypto-logstash
  #   image: 'docker.elastic.co/logstash/logstash:6.4.3'
  #   volumes:
  #     - ./docker/logstash/config:/usr/share/logstash/config:ro
  #   ports:
  #     - '5046:5046/udp'
  #   networks:
  #     - cryptocurrency

  # kibana:
  #   container_name: crypto-kibana
  #   build: docker/kibana/
  #   volumes:
  #     - ./docker/kibana/config/:/usr/share/kibana/config:ro
  #   ports:
  #     - '5601:5601'
  #   depends_on:
  #     - es
  #   networks:
  #     - cryptocurrency
